# Generated by Django 4.1.7 on 2023-03-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Group",),
        migrations.DeleteModel(name="User",),
    ]
