# Generated by Django 4.1.7 on 2023-03-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatUser",
            fields=[("id", models.IntegerField(primary_key=True, serialize=False)),],
        ),
        migrations.DeleteModel(name="User",),
        migrations.RenameModel(old_name="Group", new_name="DiscussionGroup",),
        migrations.AddField(
            model_name="chatuser",
            name="discussion_group",
            field=models.ManyToManyField(to="main_app.discussiongroup"),
        ),
    ]
