# Generated by Django 4.1.7 on 2023-03-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_remove_room_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="message",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="room",
            name="description",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
